### PR TITLE
added another iKe example: asteroids.k

### PR DESCRIPTION
**Pull request by ngn**

### CODE REVIEW

**Comment by JohnEarnest** [comment]
This is really great! I'm very excited to see that people who are not me are interested in playing with iKe.
I hope you find oK to be an "acceptable K".

**Comment by ngn** [comment]
I don't feel I'm competent enough to comment on anything k-related (my background is JS and some APL), but I certainly find oK+iKe quite enjoyable.  The combination of a terse array language, a small set of UI hooks, and a permissive license looks very promising.

**Comment by refi64** [comment]
I like this, but it's worth noting that I left my ship sitting there for at least 60 seconds before an asteroid actually hit me.

**Comment by ngn** [comment]
Feel free to tweak the constants to your liking and share the change.  `An` is the number of asteroids, `As` is their sizes.  The `25` on [this line](https://github.com/JohnEarnest/ok/blob/5a14577918ed663bd38e862117e8f48428e3ab67/ike/examples/asteroids.k#L21) is the square of the collision radius.
I admit I'm terrible as a gamer and when the asteroids start breaking down into a swarm of pebbles even the present constants can challenge my hand-eye coordination.

**Pull request merged**
